# Generated by Django 2.2.28 on 2022-12-13 20:21

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0002_auto_20221121_2217"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 15, 20, 21, 43, 558558, tzinfo=utc),
                verbose_name="актуальность ключа",
            ),
        ),
    ]
